name: Push
run-name: ${{ github.ref_name }} push run
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: read

jobs:
  windows-plugin:
    name: Build Windows plugin
    uses: ./.github/workflows/windows-plugin.yaml
